# Generated by Django 3.2.16 on 2024-04-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_tagrecipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recipe',
            name='unique_recipe',
        ),
    ]
