# Generated by Django 3.2.16 on 2024-05-01 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'default_related_name': 'ingredientamounts', 'verbose_name': 'Ингредиент для рецепта'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_related_name': 'tags', 'ordering': ('name',), 'verbose_name': 'Тэг'},
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientamounts', to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
    ]
