# Generated by Django 3.2.16 on 2024-05-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20240502_2154'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient', 'amount'), name='unique_ingredientamount'),
        ),
    ]
