# Generated by Django 3.2.16 on 2024-05-19 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_favoriterecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorited',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='is_in_shopping_cart',
        ),
    ]
