MAX_LENGTH_NAME = 200
TEXT_LENGTH = 30
FIELD_EMAIL_LEN = 254
FIELD_NAMES_LEN = 150
PROHIBITED_USERNAME = 'me'
FROM_EMAIL = 'from@foodgram.ru'
MESSAGE_NO_PERMISSION = 'You lack rights to perform this action.'
DOWNLOAD_SHOPPING_CART = 'download_shopping_cart'
SET_PASSWORD = 'set_password'
DEFAULT_TRUNCATE = 25
